# Config file for Bugs Life mod for Majora's Mask: Recompiled

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
id = "mm_bugophobia_soil_mod"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Bugophobia_soil_mod"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description = """
This mod improves the bug and soft soil mechanics in Majora's Mask: Recompiled. \
When enabled, only 1 bug needs to enter soft soil to receive the reward (instead of 3), \
and the cutscene is skipped so you maintain full control of Link while bugs enter the soil.

Features:
- Only 1 bug required per soil patch instead of 3
- No camera cutscene when bugs enter soil
- Player maintains full control during the process
- Bugs can still be scooped if desired before they fully enter"""

# A short description that will show up in this mod's entry in the mod list.
short_description = "Get soil rewards with just 1 bug and skip the cutscene."

# Authors of this mod.
authors = [ "PixelShake92" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp that this mod can run on.
minimum_recomp_version = "1.2.2"

# Dependency mods.
dependencies = []

# Optional dependency mods.
optional_dependencies = []

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = []

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_bugophobia_soil_mod"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.png" ]
